# -*- coding: utf-8 -*-
"""PINN Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdOG2N3hGuUF0koWKn6GLW_bUK_35RmT
"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

# Enforce absolute structural repeatability across runs
torch.manual_seed(42)
np.random.seed(42)

print("✅ Block 1: Deep Learning & Plotting Toolkits Successfully Bound.")

# --- Known Experimental Constants (KB Sample Reference) ---
omega_n = 2 * np.pi * 205.0  # System natural heartbeat frequency (rad/s)
omega   = 2 * np.pi * 205.0  # Shaker driving frequency at exact resonance (rad/s)
k_e2    = 0.05               # Electromechanical coupling coefficient (Eq. 10)

# Dual-load configuration parameters specified in Section 4 of the paper
R_L1 = 75000.0   # Optimal tuning resistance (75 kOhms)
R_L2 = 350000.0  # 3/4 power boundary resistance (350 kOhms)

# Target physical benchmarks for performance tracking comparison
true_zeta = 0.0117   # True mechanical damping ratio
true_Vs   = 2.560    # True source voltage magnitude (V)
true_Cp   = 10.10    # True effective internal capacitance (nF)

# --- Reparameterized Trainable Parameter Initialization ---
# We initialize our parameters with wrong guesses (0.05, 1.5V, 8.0nF)
# wrapped in log-space to enforce native positivity boundaries.
log_zeta_init = torch.nn.Parameter(torch.tensor([np.log(0.05)]), requires_grad=True)
log_Vs_init   = torch.nn.Parameter(torch.tensor([np.log(1.5)]), requires_grad=True)
log_Cp_init   = torch.nn.Parameter(torch.tensor([np.log(8.0)]), requires_grad=True)

print("✅ Block 2: Shared Trainable Parameters & Load Matrices Locked.")

class PiezoPINN(nn.Module):
    def __init__(self):
        super(PiezoPINN, self).__init__()
        # 3 Hidden Layers containing 10 Neurons each (As mandated on Page 5)
        self.input_layer   = nn.Linear(1, 10)
        self.hidden_layer1 = nn.Linear(10, 10)
        self.hidden_layer2 = nn.Linear(10, 10)
        self.output_layer  = nn.Linear(10, 2)  # Two continuous outputs: q(t) and Vp(t)

    def forward(self, t):
        # Continuous periodic signal mapping via harmonic sine routing
        x = torch.sin(self.input_layer(t))
        x = torch.sin(self.hidden_layer1(x))
        x = torch.sin(self.hidden_layer2(x))
        out = self.output_layer(x)
        return out[:, 0:1], out[:, 1:2]

# Instantiate independent twin networks to evaluate both load environments in parallel
model_R1 = PiezoPINN()
model_R2 = PiezoPINN()

print("✅ Block 3: Twin Harmonic Neural Architectures Instantiated.")

def calculate_ode_loss(model, t, Vp_data, zeta, Vs, Cp, R_L):
    # Obtain instantaneous predictions from the neural network clock entry
    q_pred, Vp_pred = model(t)

    # Execute analytical differentiation across the continuous neural graph
    dq_dt = torch.autograd.grad(q_pred, t, torch.ones_like(q_pred), create_graph=True)[0]
    d2q_dt2 = torch.autograd.grad(dq_dt, t, torch.ones_like(dq_dt), create_graph=True)[0]
    dVp_dt = torch.autograd.grad(Vp_pred, t, torch.ones_like(Vp_pred), create_graph=True)[0]

    # Evaluate dimensionless time scaling constant: r = Cp * RL * omega_n
    r_group = Cp * (1e-9) * R_L * omega_n

    # Calculate residuals for the core coupled system (Eq. 8 & Eq. 9)
    mech_residual = d2q_dt2 + 2 * zeta * dq_dt + q_pred + k_e2 * Vp_pred - Vs * k_e2 * torch.sin(t)
    elec_residual = r_group * dq_dt - r_group * dVp_dt - Vp_pred

    # Mean Squared Error evaluation
    loss_mech = torch.mean(mech_residual**2)
    loss_elec = torch.mean(elec_residual**2)
    loss_data = torch.mean((Vp_pred - Vp_data)**2)

    return loss_mech, loss_elec, loss_data

print("✅ Block 4: Analytical Physics Scoring Pipeline Configured.")

# --- Step A: Generate Synthetic Discrete Target Data Tracks ---
t_clean = np.linspace(0, 3 * (2 * np.pi), 200)  # 3 complete wave horizons
amp1 = (true_Vs * k_e2) / np.sqrt((1 - 1**2)**2 + (2 * true_zeta * 1)**2 + k_e2)
amp2 = (true_Vs * k_e2) / np.sqrt((1 - 1**2)**2 + (2 * true_zeta * 1)**2 + k_e2 * 1.5)

Vp_noisy_R1 = amp1 * np.sin(t_clean) + np.random.normal(0, 0.015, t_clean.shape)
Vp_noisy_R2 = amp2 * np.sin(t_clean) + np.random.normal(0, 0.015, t_clean.shape)

t_tensor  = torch.tensor(t_clean, dtype=torch.float32).view(-1, 1).requires_grad_(True)
Vp_exp_R1 = torch.tensor(Vp_noisy_R1, dtype=torch.float32).view(-1, 1)
Vp_exp_R2 = torch.tensor(Vp_noisy_R2, dtype=torch.float32).view(-1, 1)

# --- Step B: Establish Global Adam Optimizer ---
trainable_pool = list(model_R1.parameters()) + list(model_R2.parameters()) + [log_zeta_init, log_Vs_init, log_Cp_init]
optimizer = torch.optim.Adam(trainable_pool, lr=0.003)

# --- Step C: Arrays to Store History For The Mathematical Presentation ---
epoch_history = []
zeta_history  = []
Vs_history    = []
Cp_history    = []

print("🚀 Launching the Parameter Identification Factory at Paper Speed (LR=0.003)...\n")

for epoch in range(8001):
    optimizer.zero_grad()

    # Map back out of unconstrained space using native exponential scaling
    zeta_active = torch.exp(log_zeta_init)
    Vs_active   = torch.exp(log_Vs_init)
    Cp_active   = torch.exp(log_Cp_init)

    # Record history parameters at every epoch for plot tracking
    epoch_history.append(epoch)
    zeta_history.append(zeta_active.item())
    Vs_history.append(Vs_active.item())
    Cp_history.append(Cp_active.item())

    # Run evaluation across both experimental data environments simultaneously
    m1, e1, d1 = calculate_ode_loss(model_R1, t_tensor, Vp_exp_R1, zeta_active, Vs_active, Cp_active, R_L1)
    m2, e2, d2 = calculate_ode_loss(model_R2, t_tensor, Vp_exp_R2, zeta_active, Vs_active, Cp_active, R_L2)

    # Total integration weighted with paper parameters (wf1=0.5, wf2=0.5, we=1.0)
    total_loss = (0.5*m1 + 0.5*e1 + 1.0*d1) + (0.5*m2 + 0.5*e2 + 1.0*d2)

    total_loss.backward()
    optimizer.step()

    if epoch % 2000 == 0:
        print(f"Iteration {epoch:5d} | Combined Loss: {total_loss.item():.5f}")
        print(f"   ↳ Extracted Extrapolations -> ζm: {zeta_active.item():.4f} | Vs: {Vs_active.item():.3f}V | Cp: {Cp_active.item():.2f} nF")
        print("-" * 95)

# =====================================================================
# --- Step D: RENDER PARAMETER CONVERGENCE HISTORIES (Replicating Figs 3 & 4) ---
# =====================================================================
fig, axs = plt.subplots(1, 3, figsize=(18, 5))

# Plot 1: Mechanical Damping Convergency (ζm)
axs[0].plot(epoch_history, zeta_history, color='forestgreen', linewidth=2.5, label='PINN Inverse Identified $\zeta_m$')
axs[0].axhline(y=true_zeta, color='gray', linestyle='--', linewidth=2, label=f'Ground Truth ({true_zeta})')
axs[0].set_title("Mechanical Damping Ratio $\zeta_m$ Convergence")
axs[0].set_xlabel("Training Iterations")
axs[0].set_ylabel("Damping Value $\zeta_m$")
axs[0].grid(True, linestyle=':')
axs[0].legend()

# Plot 2: Source Input Force Voltage Convergency (Vs)
axs[1].plot(epoch_history, Vs_history, color='deepskyblue', linewidth=2.5, label='PINN Inverse Identified $V_s$')
axs[1].axhline(y=true_Vs, color='gray', linestyle='--', linewidth=2, label=f'Ground Truth ({true_Vs}V)')
axs[1].set_title("Source Voltage Magnitude $V_s$ Convergence")
axs[1].set_xlabel("Training Iterations")
axs[1].set_ylabel("Voltage Magnitude (V)")
axs[1].grid(True, linestyle=':')
axs[1].legend()

# Plot 3: Effective Piezo Capacitor Capacity Convergency (Cp)
axs[2].plot(epoch_history, Cp_history, color='crimson', linewidth=2.5, label='PINN Inverse Identified $C_p$')
axs[2].axhline(y=true_Cp, color='gray', linestyle='--', linewidth=2, label=f'Ground Truth ({true_Cp} nF)')
axs[2].set_title("Piezoelectric Capacitance $C_p$ Convergence")
axs[2].set_xlabel("Training Iterations")
axs[2].set_ylabel("Capacitance Scale (nF)")
axs[2].grid(True, linestyle=':')
axs[2].legend()

plt.tight_layout()
plt.show()

plt.savefig("Parameter_graphs.png")