# -*- coding: utf-8 -*-
"""PINN_Model_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gF4_IXGNgLuHTi4LEDxbPz3M2EczHAKv
"""

# CODE FOR SETUP:1

# =========================
# BLOCK 1: SETUP & CONSTANTS
# =========================
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
torch.manual_seed(42)
np.random.seed(42)
print("✅ Block 1: Setup complete")

omega_n = 2 * np.pi * 205.0   # ωn (rad/s) — used in r = Cp·RL·ωn only
f_exc = 205   # shaker frequency in Hz
omega_exc = 2 * np.pi * f_exc
Omega = omega_exc / omega_n

k_e2    = 0.05                 # electromechanical coupling coefficient ke²
R_L1    = 75000.0              # load 1 (Ω)
R_L2    = 350000.0             # load 2 (Ω)

# True values — used ONLY for final validation, NEVER in training
# QA sample true values
true_zeta = 0.0117
true_Vs   = 2.560
true_Cp   = 10.10e-9

# Trainable parameters in log-space (ensures positivity)
# Initialised with engineering guesses, not true values
log_zeta = nn.Parameter(torch.tensor([np.log(0.006)], dtype=torch.float32))
log_Vs   = nn.Parameter(torch.tensor([np.log(1.7)], dtype=torch.float32))
log_Cp   = nn.Parameter(torch.tensor([np.log(9e-9)], dtype=torch.float32))

print(f"Initial guesses (engineering estimates, not true values):")
print(f"  ζ  = 0.0117  (true: {true_zeta})")
print(f"  Vs = 2.560  (true: {true_Vs})")
print(f"  Cp = 10.10e-9  (true: {true_Cp:.3e})")


# =========================
# BLOCK 2: MODEL DEFINITION
# =========================
# Architecture exactly as paper (Section 4, page 5):
#   - 3 hidden layers, 10 neurons each
#   - Sine activation function
#   - Single network taking [t̄, R_L_norm] as input
#     (paper inputs: t̄, R_L, ω — here ω is fixed at resonance so only t̄ and R_L vary)

class PiezoPINN(nn.Module):
    def __init__(self):
        super().__init__()
        # omega_0 controls SIREN internal frequency.
        # Data oscillates at ~1 rad/t̄ (resonance with dimensionless time).
        # omega_0 = 1.0 is appropriate for this frequency range.
        self.omega_0 = 1.0
        self.input_layer  = nn.Linear(2, 10)   # 2 inputs: [t̄, R_L_normalised]
        self.hidden1      = nn.Linear(10, 10)
        self.hidden2      = nn.Linear(10, 10)
        self.hidden3      = nn.Linear(10, 10)
        self.output_layer = nn.Linear(10, 2)
        self._init_weights()

    def _init_weights(self):
        # SIREN initialisation (Sitzmann et al., 2020)
        with torch.no_grad():
            self.input_layer.weight.uniform_(-1.0, 1.0)
            self.hidden1.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)
            self.hidden2.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)
            self.hidden3.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)
            self.output_layer.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)

    def forward(self, t, RL_norm):
        inp = torch.cat([t, RL_norm], dim=1)
        x   = torch.sin(self.omega_0 * self.input_layer(inp))
        x   = torch.sin(self.hidden1(x))
        x   = torch.sin(self.hidden2(x))
        x   = torch.sin(self.hidden3(x))
        out = self.output_layer(x)
        return out[:, 0:1], out[:, 1:2]   # outputs: q(t̄), Vp(t̄)

model = PiezoPINN()
print("✅ Block 2: Single network — inputs [t̄, R_L_norm], 3×10 neurons, sine activation")


# =========================
# BLOCK 3: PHYSICS + DATA LOSS
# =========================
def calculate_physics_loss(model, t, RL_norm, zeta, Vs, Cp, R_L):
    """Evaluates ODE residuals on dense collocation points (no data needed)"""
    q_pred, Vp_pred = model(t, RL_norm)

    dq_dt   = torch.autograd.grad(q_pred,  t, grad_outputs=torch.ones_like(q_pred),  create_graph=True)[0]
    d2q_dt2 = torch.autograd.grad(dq_dt,   t, grad_outputs=torch.ones_like(dq_dt),   create_graph=True)[0]
    dVp_dt  = torch.autograd.grad(Vp_pred, t, grad_outputs=torch.ones_like(Vp_pred), create_graph=True)[0]

    r = Cp * R_L * omega_n

    # Mechanical ODE
    mech_res = d2q_dt2 + 2*zeta*dq_dt + q_pred + k_e2*Vp_pred - k_e2*Vs*torch.sin(Omega*t)

    # Electrical ODE (RESTORED THE 'r' TO MATCH YOUR DATA GENERATOR!)
    elec_res = r*dq_dt - r*dVp_dt - Vp_pred

    loss_mech = torch.mean(mech_res**2)
    loss_elec = torch.mean(elec_res**2)
    return loss_mech, loss_elec

def calculate_data_loss(model, t_data, RL_norm_data, Vp_true):
    """Evaluates voltage prediction only at the sparse experimental timestamps"""
    _, Vp_pred = model(t_data, RL_norm_data)
    return torch.mean((Vp_pred - Vp_true)**2)

print("✅ Block 3: Physics and Data loss functions cleanly separated, MATH FIXED")


# =========================
# BLOCK 4: DATA GENERATION & COLLOCATION
# =========================
print("⚙️  Generating data and independent collocation points ...")
t_span = (0.0, 3*(2*np.pi)/Omega)
t_eval = np.linspace(t_span[0], t_span[1], 200) # 200 Experimental points
y0     = [0.0, 0.0, 0.0]

def piezo_ode(t, y, zeta, Vs, Cp, R_L):
    q, dqdt, Vp = y
    r = Cp * R_L * omega_n
    d2qdt2 = -2*zeta*dqdt - q - k_e2*Vp + k_e2*Vs*np.sin(Omega*t)
    dVpdt  = dqdt - (1.0/r)*Vp
    return [dqdt, d2qdt2, dVpdt]

sol1 = solve_ivp(piezo_ode, t_span, y0, t_eval=t_eval, args=(true_zeta, true_Vs, true_Cp, R_L1), rtol=1e-8, atol=1e-10)
sol2 = solve_ivp(piezo_ode, t_span, y0, t_eval=t_eval, args=(true_zeta, true_Vs, true_Cp, R_L2), rtol=1e-8, atol=1e-10)

Vp_R1 = sol1.y[2] + np.random.normal(0, 0.001, len(t_eval))
Vp_R2 = sol2.y[2] + np.random.normal(0, 0.001, len(t_eval))

# --- Experimental Data Tensors ---
t_tensor     = torch.tensor(t_eval, dtype=torch.float32).view(-1,1).requires_grad_(True)
Vp_tensor_R1 = torch.tensor(Vp_R1,  dtype=torch.float32).view(-1,1)
Vp_tensor_R2 = torch.tensor(Vp_R2,  dtype=torch.float32).view(-1,1)

R_L_max    = max(R_L1, R_L2)
RL1_tensor = torch.full((len(t_eval), 1), R_L1/R_L_max, dtype=torch.float32)
RL2_tensor = torch.full((len(t_eval), 1), R_L2/R_L_max, dtype=torch.float32)

# --- NEW: Continuous Physics Collocation Points ---
# 500 points where the model MUST obey the ODEs, with no experimental data attached
t_phys_eval = np.linspace(t_span[0], t_span[1], 500)
t_physics_tensor = torch.tensor(t_phys_eval, dtype=torch.float32).view(-1,1).requires_grad_(True)
RL1_physics = torch.full((len(t_phys_eval), 1), R_L1/R_L_max, dtype=torch.float32)
RL2_physics = torch.full((len(t_phys_eval), 1), R_L2/R_L_max, dtype=torch.float32)

optimizer = torch.optim.Adam(list(model.parameters()) + [log_zeta, log_Vs, log_Cp], lr=0.003)
print("✅ Block 4: Data & Collocation ready")


# =========================
# BLOCK 5: ROBUST TRAINING
# =========================
wf1, wf2, we = 0.5, 0.5, 1.0
epochs = 8000
epoch_history, zeta_history, Vs_history, Cp_history, loss_history = [], [], [], [], []

for epoch in range(epochs + 1):
    optimizer.zero_grad()

    zeta = torch.exp(log_zeta)
    Vs   = torch.exp(log_Vs)
    Cp   = torch.exp(log_Cp)

    # 1. Physics Loss on dense collocation points
    m1, e1 = calculate_physics_loss(model, t_physics_tensor, RL1_physics, zeta, Vs, Cp, R_L1)
    m2, e2 = calculate_physics_loss(model, t_physics_tensor, RL2_physics, zeta, Vs, Cp, R_L2)

    # 2. Data Loss on sparse experimental points
    d1 = calculate_data_loss(model, t_tensor, RL1_tensor, Vp_tensor_R1)
    d2 = calculate_data_loss(model, t_tensor, RL2_tensor, Vp_tensor_R2)

    # Total Loss Eq. (11)
    total_loss = (wf1*m1 + wf2*e1 + we*d1) + (wf1*m2 + wf2*e2 + we*d2)

    total_loss.backward()
    torch.nn.utils.clip_grad_norm_(list(model.parameters()) + [log_zeta, log_Vs, log_Cp], max_norm=1.0)
    optimizer.step()

    epoch_history.append(epoch)
    zeta_history.append(zeta.item())
    Vs_history.append(Vs.item())
    Cp_history.append(Cp.item() * 1e9)
    loss_history.append(total_loss.item())

    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d} | Loss: {total_loss.item():.6f}")
        print(f"   ζ  = {zeta.item():.6f}  (true {true_zeta}, error {abs(zeta.item()-true_zeta)/true_zeta*100:.2f}%)")
        print(f"   Vs = {Vs.item():.6f} V  (true {true_Vs}, error {abs(Vs.item()-true_Vs)/true_Vs*100:.2f}%)")
        print(f"   Cp = {Cp.item()*1e9:.4f} nF  (true {true_Cp*1e9}, error {abs(Cp.item()-true_Cp)/true_Cp*100:.2f}%)")
        print("-" * 65)

zeta_f = torch.exp(log_zeta).item()
Vs_f   = torch.exp(log_Vs).item()
Cp_f   = torch.exp(log_Cp).item()

print("\n" + "="*65)
print("FINAL RESULTS — Robust PINN (No Data Leakage)")
print("="*65)
print(f"ζ  = {zeta_f:.6f}  (true {true_zeta},  error {abs(zeta_f-true_zeta)/true_zeta*100:.2f}%)")
print(f"Vs = {Vs_f:.6f} V  (true {true_Vs},  error {abs(Vs_f-true_Vs)/true_Vs*100:.2f}%)")
print(f"Cp = {Cp_f*1e9:.4f} nF  (true {true_Cp*1e9},  error {abs(Cp_f-true_Cp)/true_Cp*100:.2f}%)")
print("="*65)


# =========================
# BLOCK 6: FINAL PLOTS
# =========================
with torch.no_grad():
    _, Vp1 = model(t_tensor, RL1_tensor)
    _, Vp2 = model(t_tensor, RL2_tensor)

t_np = t_tensor.detach().numpy().flatten()
fig, axs = plt.subplots(2, 2, figsize=(16, 10))

axs[0,0].plot(t_np, Vp_R1, lw=2, label="ODE Data")
axs[0,0].plot(t_np, Vp1.numpy().flatten(), '--', lw=2, label="PINN Prediction")
axs[0,0].set_title(r"Voltage — $R_{L1}=75\,k\Omega$", fontsize=13, fontweight='bold')
axs[0,0].set_xlabel(r"Dimensionless time $\bar{t}$")
axs[0,0].set_ylabel("Voltage (V)")
axs[0,0].grid(linestyle=':'); axs[0,0].legend()

axs[0,1].plot(t_np, Vp_R2, lw=2, label="ODE Data")
axs[0,1].plot(t_np, Vp2.numpy().flatten(), '--', lw=2, label="PINN Prediction")
axs[0,1].set_title(r"Voltage — $R_{L2}=350\,k\Omega$", fontsize=13, fontweight='bold')
axs[0,1].set_xlabel(r"Dimensionless time $\bar{t}$")
axs[0,1].set_ylabel("Voltage (V)")
axs[0,1].grid(linestyle=':'); axs[0,1].legend()

axs[1,0].plot(epoch_history, zeta_history, lw=2, label=r"$\zeta_m$")
axs[1,0].plot(epoch_history, Vs_history,   lw=2, label=r"$V_s$ (V)")
axs[1,0].plot(epoch_history, Cp_history,   lw=2, label=r"$C_p$ (nF)")
axs[1,0].axhline(true_zeta,   color='C0', ls='--', alpha=0.5, label='True values')
axs[1,0].axhline(true_Vs,     color='C1', ls='--', alpha=0.5)
axs[1,0].axhline(true_Cp*1e9, color='C2', ls='--', alpha=0.5)
axs[1,0].set_title("Parameter Convergence", fontsize=13, fontweight='bold')
axs[1,0].set_xlabel("Epochs"); axs[1,0].set_ylabel("Value")
axs[1,0].grid(linestyle=':'); axs[1,0].legend(fontsize=9)

axs[1,1].semilogy(epoch_history, loss_history, lw=2, color='green')
axs[1,1].set_title("Total Loss (log scale)", fontsize=13, fontweight='bold')
axs[1,1].set_xlabel("Epochs"); axs[1,1].set_ylabel("Loss")
axs[1,1].grid(linestyle=':', which='both')

plt.tight_layout()
plt.savefig("PINN_final_submission.png", dpi=300, bbox_inches='tight')
plt.show()
print("✅ Saved: PINN_final_submission.png")

# CODE FOR SETUP:2

# =========================
# BLOCK 1: SETUP & CONSTANTS
# =========================
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
torch.manual_seed(42)
np.random.seed(42)
print("✅ Block 1: Setup complete")

omega_n = 2 * np.pi * 205.0   # ωn (rad/s) — used in r = Cp·RL·ωn only
f_exc = 205   # shaker frequency in Hz
omega_exc = 2 * np.pi * f_exc
Omega = omega_exc / omega_n

k_e2    = 0.15                 # electromechanical coupling coefficient ke²
R_L1    = 75000.0              # load 1 (Ω)
R_L2    = 500000.0             # load 2 (Ω)

# True values — used ONLY for final validation, NEVER in training
# QA sample true values
true_zeta = 0.00405
true_Vs   = 1.88
true_Cp   = 9.89e-9

# Trainable parameters in log-space (ensures positivity)
# Initialised with engineering guesses, not true values
log_zeta = nn.Parameter(torch.tensor([np.log(0.006)], dtype=torch.float32))
log_Vs   = nn.Parameter(torch.tensor([np.log(1.7)], dtype=torch.float32))
log_Cp   = nn.Parameter(torch.tensor([np.log(9e-9)], dtype=torch.float32))

print(f"Initial guesses (engineering estimates, not true values):")
print(f"  ζ  = 0.00504  (true: {true_zeta})")
print(f"  Vs = 1.88   (true: {true_Vs})")
print(f"  Cp = 9.89e-9  (true: {true_Cp:.3e})")


# =========================
# BLOCK 2: MODEL DEFINITION
# =========================
# Architecture exactly as paper (Section 4, page 5):
#   - 3 hidden layers, 10 neurons each
#   - Sine activation function
#   - Single network taking [t̄, R_L_norm] as input
#     (paper inputs: t̄, R_L, ω — here ω is fixed at resonance so only t̄ and R_L vary)

class PiezoPINN(nn.Module):
    def __init__(self):
        super().__init__()
        # omega_0 controls SIREN internal frequency.
        # Data oscillates at ~1 rad/t̄ (resonance with dimensionless time).
        # omega_0 = 1.0 is appropriate for this frequency range.
        self.omega_0 = 1.0
        self.input_layer  = nn.Linear(2, 10)   # 2 inputs: [t̄, R_L_normalised]
        self.hidden1      = nn.Linear(10, 10)
        self.hidden2      = nn.Linear(10, 10)
        self.hidden3      = nn.Linear(10, 10)
        self.output_layer = nn.Linear(10, 2)
        self._init_weights()

    def _init_weights(self):
        # SIREN initialisation (Sitzmann et al., 2020)
        with torch.no_grad():
            self.input_layer.weight.uniform_(-1.0, 1.0)
            self.hidden1.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)
            self.hidden2.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)
            self.hidden3.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)
            self.output_layer.weight.uniform_(-np.sqrt(6/10)/self.omega_0, np.sqrt(6/10)/self.omega_0)

    def forward(self, t, RL_norm):
        inp = torch.cat([t, RL_norm], dim=1)
        x   = torch.sin(self.omega_0 * self.input_layer(inp))
        x   = torch.sin(self.hidden1(x))
        x   = torch.sin(self.hidden2(x))
        x   = torch.sin(self.hidden3(x))
        out = self.output_layer(x)
        return out[:, 0:1], out[:, 1:2]   # outputs: q(t̄), Vp(t̄)

model = PiezoPINN()
print("✅ Block 2: Single network — inputs [t̄, R_L_norm], 3×10 neurons, sine activation")


# =========================
# BLOCK 3: PHYSICS + DATA LOSS
# =========================
def calculate_physics_loss(model, t, RL_norm, zeta, Vs, Cp, R_L):
    """Evaluates ODE residuals on dense collocation points (no data needed)"""
    q_pred, Vp_pred = model(t, RL_norm)

    dq_dt   = torch.autograd.grad(q_pred,  t, grad_outputs=torch.ones_like(q_pred),  create_graph=True)[0]
    d2q_dt2 = torch.autograd.grad(dq_dt,   t, grad_outputs=torch.ones_like(dq_dt),   create_graph=True)[0]
    dVp_dt  = torch.autograd.grad(Vp_pred, t, grad_outputs=torch.ones_like(Vp_pred), create_graph=True)[0]

    r = Cp * R_L * omega_n

    # Mechanical ODE
    mech_res = d2q_dt2 + 2*zeta*dq_dt + q_pred + k_e2*Vp_pred - k_e2*Vs*torch.sin(Omega*t)

    # Electrical ODE (RESTORED THE 'r' TO MATCH YOUR DATA GENERATOR!)
    elec_res = r*dq_dt - r*dVp_dt - Vp_pred

    loss_mech = torch.mean(mech_res**2)
    loss_elec = torch.mean(elec_res**2)
    return loss_mech, loss_elec

def calculate_data_loss(model, t_data, RL_norm_data, Vp_true):
    """Evaluates voltage prediction only at the sparse experimental timestamps"""
    _, Vp_pred = model(t_data, RL_norm_data)
    return torch.mean((Vp_pred - Vp_true)**2)

print("✅ Block 3: Physics and Data loss functions cleanly separated, MATH FIXED")


# =========================
# BLOCK 4: DATA GENERATION & COLLOCATION
# =========================
print("⚙️  Generating data and independent collocation points ...")
t_span = (0.0, 3*(2*np.pi)/Omega)
t_eval = np.linspace(t_span[0], t_span[1], 200) # 200 Experimental points
y0     = [0.0, 0.0, 0.0]

def piezo_ode(t, y, zeta, Vs, Cp, R_L):
    q, dqdt, Vp = y
    r = Cp * R_L * omega_n
    d2qdt2 = -2*zeta*dqdt - q - k_e2*Vp + k_e2*Vs*np.sin(Omega*t)
    dVpdt  = dqdt - (1.0/r)*Vp
    return [dqdt, d2qdt2, dVpdt]

sol1 = solve_ivp(piezo_ode, t_span, y0, t_eval=t_eval, args=(true_zeta, true_Vs, true_Cp, R_L1), rtol=1e-8, atol=1e-10)
sol2 = solve_ivp(piezo_ode, t_span, y0, t_eval=t_eval, args=(true_zeta, true_Vs, true_Cp, R_L2), rtol=1e-8, atol=1e-10)

Vp_R1 = sol1.y[2] + np.random.normal(0, 0.001, len(t_eval))
Vp_R2 = sol2.y[2] + np.random.normal(0, 0.001, len(t_eval))

# --- Experimental Data Tensors ---
t_tensor     = torch.tensor(t_eval, dtype=torch.float32).view(-1,1).requires_grad_(True)
Vp_tensor_R1 = torch.tensor(Vp_R1,  dtype=torch.float32).view(-1,1)
Vp_tensor_R2 = torch.tensor(Vp_R2,  dtype=torch.float32).view(-1,1)

R_L_max    = max(R_L1, R_L2)
RL1_tensor = torch.full((len(t_eval), 1), R_L1/R_L_max, dtype=torch.float32)
RL2_tensor = torch.full((len(t_eval), 1), R_L2/R_L_max, dtype=torch.float32)

# --- NEW: Continuous Physics Collocation Points ---
# 500 points where the model MUST obey the ODEs, with no experimental data attached
t_phys_eval = np.linspace(t_span[0], t_span[1], 500)
t_physics_tensor = torch.tensor(t_phys_eval, dtype=torch.float32).view(-1,1).requires_grad_(True)
RL1_physics = torch.full((len(t_phys_eval), 1), R_L1/R_L_max, dtype=torch.float32)
RL2_physics = torch.full((len(t_phys_eval), 1), R_L2/R_L_max, dtype=torch.float32)

optimizer = torch.optim.Adam(list(model.parameters()) + [log_zeta, log_Vs, log_Cp], lr=0.003)
print("✅ Block 4: Data & Collocation ready")


# =========================
# BLOCK 5: ROBUST TRAINING
# =========================
wf1, wf2, we = 0.5, 0.5, 1.0
epochs = 8000
epoch_history, zeta_history, Vs_history, Cp_history, loss_history = [], [], [], [], []

for epoch in range(epochs + 1):
    optimizer.zero_grad()

    zeta = torch.exp(log_zeta)
    Vs   = torch.exp(log_Vs)
    Cp   = torch.exp(log_Cp)

    # 1. Physics Loss on dense collocation points
    m1, e1 = calculate_physics_loss(model, t_physics_tensor, RL1_physics, zeta, Vs, Cp, R_L1)
    m2, e2 = calculate_physics_loss(model, t_physics_tensor, RL2_physics, zeta, Vs, Cp, R_L2)

    # 2. Data Loss on sparse experimental points
    d1 = calculate_data_loss(model, t_tensor, RL1_tensor, Vp_tensor_R1)
    d2 = calculate_data_loss(model, t_tensor, RL2_tensor, Vp_tensor_R2)

    # Total Loss Eq. (11)
    total_loss = (wf1*m1 + wf2*e1 + we*d1) + (wf1*m2 + wf2*e2 + we*d2)

    total_loss.backward()
    torch.nn.utils.clip_grad_norm_(list(model.parameters()) + [log_zeta, log_Vs, log_Cp], max_norm=1.0)
    optimizer.step()

    epoch_history.append(epoch)
    zeta_history.append(zeta.item())
    Vs_history.append(Vs.item())
    Cp_history.append(Cp.item() * 1e9)
    loss_history.append(total_loss.item())

    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d} | Loss: {total_loss.item():.6f}")
        print(f"   ζ  = {zeta.item():.6f}  (true {true_zeta}, error {abs(zeta.item()-true_zeta)/true_zeta*100:.2f}%)")
        print(f"   Vs = {Vs.item():.6f} V  (true {true_Vs}, error {abs(Vs.item()-true_Vs)/true_Vs*100:.2f}%)")
        print(f"   Cp = {Cp.item()*1e9:.4f} nF  (true {true_Cp*1e9}, error {abs(Cp.item()-true_Cp)/true_Cp*100:.2f}%)")
        print("-" * 65)

zeta_f = torch.exp(log_zeta).item()
Vs_f   = torch.exp(log_Vs).item()
Cp_f   = torch.exp(log_Cp).item()

print("\n" + "="*65)
print("FINAL RESULTS — Robust PINN (No Data Leakage)")
print("="*65)
print(f"ζ  = {zeta_f:.6f}  (true {true_zeta},  error {abs(zeta_f-true_zeta)/true_zeta*100:.2f}%)")
print(f"Vs = {Vs_f:.6f} V  (true {true_Vs},  error {abs(Vs_f-true_Vs)/true_Vs*100:.2f}%)")
print(f"Cp = {Cp_f*1e9:.4f} nF  (true {true_Cp*1e9},  error {abs(Cp_f-true_Cp)/true_Cp*100:.2f}%)")
print("="*65)


# =========================
# BLOCK 6: FINAL PLOTS
# =========================
with torch.no_grad():
    _, Vp1 = model(t_tensor, RL1_tensor)
    _, Vp2 = model(t_tensor, RL2_tensor)

t_np = t_tensor.detach().numpy().flatten()
fig, axs = plt.subplots(2, 2, figsize=(16, 10))

axs[0,0].plot(t_np, Vp_R1, lw=2, label="ODE Data")
axs[0,0].plot(t_np, Vp1.numpy().flatten(), '--', lw=2, label="PINN Prediction")
axs[0,0].set_title(r"Voltage — $R_{L1}=75\,k\Omega$", fontsize=13, fontweight='bold')
axs[0,0].set_xlabel(r"Dimensionless time $\bar{t}$")
axs[0,0].set_ylabel("Voltage (V)")
axs[0,0].grid(linestyle=':'); axs[0,0].legend()

axs[0,1].plot(t_np, Vp_R2, lw=2, label="ODE Data")
axs[0,1].plot(t_np, Vp2.numpy().flatten(), '--', lw=2, label="PINN Prediction")
axs[0,1].set_title(r"Voltage — $R_{L2}=350\,k\Omega$", fontsize=13, fontweight='bold')
axs[0,1].set_xlabel(r"Dimensionless time $\bar{t}$")
axs[0,1].set_ylabel("Voltage (V)")
axs[0,1].grid(linestyle=':'); axs[0,1].legend()

axs[1,0].plot(epoch_history, zeta_history, lw=2, label=r"$\zeta_m$")
axs[1,0].plot(epoch_history, Vs_history,   lw=2, label=r"$V_s$ (V)")
axs[1,0].plot(epoch_history, Cp_history,   lw=2, label=r"$C_p$ (nF)")
axs[1,0].axhline(true_zeta,   color='C0', ls='--', alpha=0.5, label='True values')
axs[1,0].axhline(true_Vs,     color='C1', ls='--', alpha=0.5)
axs[1,0].axhline(true_Cp*1e9, color='C2', ls='--', alpha=0.5)
axs[1,0].set_title("Parameter Convergence", fontsize=13, fontweight='bold')
axs[1,0].set_xlabel("Epochs"); axs[1,0].set_ylabel("Value")
axs[1,0].grid(linestyle=':'); axs[1,0].legend(fontsize=9)

axs[1,1].semilogy(epoch_history, loss_history, lw=2, color='green')
axs[1,1].set_title("Total Loss (log scale)", fontsize=13, fontweight='bold')
axs[1,1].set_xlabel("Epochs"); axs[1,1].set_ylabel("Loss")
axs[1,1].grid(linestyle=':', which='both')

plt.tight_layout()
plt.savefig("PINN_final_submission.png", dpi=300, bbox_inches='tight')
plt.show()
print("✅ Saved: PINN_final_submission.png")